### ISSUE TITLE
Handle _graphics, mod and vendors

### ISSUE THREAD

**Issue by Srokap** [Elgg/starter-project#1]
We need to handle static assets without routing them through php (though in case of mod dir it might not be that terrible idea)

My initial looking into more complex compser installer for core did not give much joy, so current idea is to just utilize [composer events](https://getcomposer.org/doc/articles/scripts.md#event-names) and run a script to copy/link particular files.
- remember to handle updates and be careful about bundled plugins

**Comment by ewinslow** [comment]
Or we could require that folks rite these resources through the views system? That would be OK for 2.0. We can explicitly disallow direct access to mod or vendor directory via the htaxcess configuration

**Comment by ewinslow** [comment]
It would also be note correct since simple cache supports cache busting but static files do not.

**Comment by ewinslow** [comment]
More correct*

**Comment by ewinslow** [comment]
So, regarding the performance issue, I think we just need a simple way to optionally cache the assets in the web root and we'll be fine. With our switch to Stash this should actually be really simple, since they have a file system-based cache adapter already...

**Comment by ewinslow** [comment]
I added some rewrite-rules that forwards from vendors/\* to vendor/elgg/elgg/vendors/*. Same with _graphics. I think this gets us 90% there. There's still the issue of static assets and even page handlers served directly from /mod/. A couple of steps we can take:
1. Add another rewrite rule that takes all /mod/\* requests that don't already match a file and forwards them to vendor/elgg/elgg/mod/*. Quick and easy. Works cross-platform.
2. Add some composer commands that automatically copy all core plugins from vendor/elgg/elgg/mod/ to /mod/. This probably wouldn't work for Windows for trivial implementations. I'm ok with that for the short term. We'd want to get windows support back quickly, though. Once that's done this change might also allow us to stop using your custom fork of Elgg, since the engine would not have to know how to load plugins from two locations anymore.
3. Extract all plugins from elgg/elgg such that they are installed as separate repos and therefore listed at the root /mod/ directory by default.
4. Edit plugins such that they serve all pages and/or static assets through the views system, not directly through /mod/*.

**Comment by ewinslow** [comment]
All static assets can be routed through the views system now.
